
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/blog?useTimezone=true&serverTimezone=UTC&uselegacyDate
    username: postgres
    password: 1414
  jpa: 
    show-sql: true
    hibernate: 
      ddl-auto: update
    properties:
      hibernate.format_sql: true
    
logging:
   level:   
     org:
       hibernate:
         type: trace
        

      

